export const ourPartnerSectionText = {
  heading1: "OUR ",
  heading2: "PARTNERS",
  imagesList: [
    {
      pathName: "/logo/our-partner/CM_night_market.png",
      pathNameWebP: "/logo/our-partner/CM_night_market.webp",
      className: "rounded-full",
      alt: "semour logo",
      urlName: "https://www.facebook.com/cmnightmarket/",
    },
    {
      pathName: "/logo/our-partner/Pundee.png",
      pathNameWebP: "/logo/our-partner/Pundee.webp",
      className: "rounded-full",
      alt: "semour logo",
      urlName: "https://www.facebook.com/phandee.th/",
    },
    {
      pathName: "/logo/our-partner/tonsai_market.png",
      pathNameWebP: "/logo/our-partner/tonsai_market.webp",
      alt: "Tonsai market logo",
      urlName: "https://www.facebook.com/Tonsaimarket456",
    },
    {
      pathName: "/logo/our-partner/KS_seaport.png",
      pathNamewebP: "/logo/our-partner/KS_seaport.webp",
      alt: "KS seaport logo",
      urlName:
        "https://wwww.facebook.com/p/KS-Sea-Port-Company-Limited-100054525187944",
    },
    {
      pathName: "/logo/our-partner/Scg-logo.png",
      pathNameWebP: "/logo/our-partner/Scg-logo.webp",
      alt: "SCG logo",
      urlName: "https://www.scg.com/landing/",
    },
    {
      pathName: "/logo/our-partner/scgc-logo.png",
      pathNameWebP: "/logo/our-partner/scgc-logo.webp",
      alt: "SCGC logo",
      urlName: "https://www.scgchemicals.com/th/home",
    },
    {
      pathName: "/logo/our-partner/chavarak-logo.png",
      pathNameWebP: "/logo/our-partner/chavarak-logo.webp",
      alt: "chavarak logo",
      urlName: "https://chavarakpipe.com/",
    },
    {
      pathName: "/logo/our-partner/semour.png",
      pathNameWebP: "/logo/our-partner/semour.webp",
      alt: "semour logo",
      urlName: "https://seamoormarine.com",
    },
    {
      pathName: "/logo/our-partner/siam-tara-logo.jpg",
      pathNameWebP: "/logo/our-partner/siam-tara-logo.webp",
      alt: "siam tara logo",
      urlName: "",
    },
    {
      pathName: "/logo/our-partner/The_Pine.png",
      pathNameWebP: "/logo/our-partner/The_Pine.webp",
      className: "rounded-full",
      alt: "semour logo",
      urlName: "https://www.facebook.com/ThePineSongkhla/",
    },
    {
      pathName: "/logo/our-partner/APT_bearing_mall.png",
      pathNameWebP: "/logo/our-partner/APT_bearing_mall.webp",
      className: "rounded-full",
      alt: "semour logo",
      urlName: "https://www.facebook.com/aptbearing/",
    },

    {
      pathName: "/logo/our-partner/CM_night_market.png",
      pathNameWebP: "/logo/our-partner/CM_night_market.webp",
      className: "rounded-full",
      alt: "semour logo",
      urlName: "https://www.facebook.com/cmnightmarket/",
    },
    {
      pathName: "/logo/our-partner/Pundee.png",
      pathNameWebP: "/logo/our-partner/Pundee.webp",
      className: "rounded-full",
      alt: "semour logo",
      urlName: "https://www.facebook.com/phandee.th/",
    },
    {
      pathName: "/logo/our-partner/tonsai_market.png",
      pathNameWebP: "/logo/our-partner/tonsai_market.webp",
      alt: "Tonsai market logo",
      urlName: "https://www.facebook.com/Tonsaimarket456",
    },
    {
      pathName: "/logo/our-partner/KS_seaport.png",
      pathNamewebP: "/logo/our-partner/KS_seaport.webp",
      alt: "KS seaport logo",
      urlName:
        "https://wwww.facebook.com/p/KS-Sea-Port-Company-Limited-100054525187944",
    },
    {
      pathName: "/logo/our-partner/Scg-logo.png",
      pathNameWebP: "/logo/our-partner/Scg-logo.webp",
      alt: "SCG logo",
      urlName: "https://www.scg.com/landing/",
    },
    {
      pathName: "/logo/our-partner/scgc-logo.png",
      pathNameWebP: "/logo/our-partner/scgc-logo.webp",
      alt: "SCGC logo",
      urlName: "https://www.scgchemicals.com/th/home",
    },
    {
      pathName: "/logo/our-partner/chavarak-logo.png",
      pathNameWebP: "/logo/our-partner/chavarak-logo.webp",
      alt: "chavarak logo",
      urlName: "https://chavarakpipe.com/",
    },
    {
      pathName: "/logo/our-partner/semour.png",
      pathNameWebP: "/logo/our-partner/semour.webp",
      alt: "semour logo",
      urlName: "https://seamoormarine.com",
    },
    {
      pathName: "/logo/our-partner/siam-tara-logo.jpg",
      pathNameWebP: "/logo/our-partner/siam-tara-logo.webp",
      alt: "siam tara logo",
      urlName: "",
    },
    {
      pathName: "/logo/our-partner/The_Pine.png",
      pathNameWebP: "/logo/our-partner/The_Pine.webp",
      className: "rounded-full",
      alt: "semour logo",
      urlName: "https://www.facebook.com/ThePineSongkhla/",
    },
    {
      pathName: "/logo/our-partner/APT_bearing_mall.png",
      pathNameWebP: "/logo/our-partner/APT_bearing_mall.webp",
      className: "rounded-full",
      alt: "semour logo",
      urlName: "https://www.facebook.com/aptbearing/",
    },
  ],
};
